{% set name = "plsdbapi" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: master
  git_url: https://github.com/CCB-SB/plsdbapi

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.9
    - requests >=2.25
    - pandas >=1.2.5
    - tqdm >=4.62.1

test:
  imports:
    - plsdbapi

about:
  home: https://www.ccb.uni-saarland.de/plsdb
  license: MIT
  license_family: MIT
  summary: API for plasmid database PLSDB
  dev_url: https://github.com/CCB-SB/plsdbapi 